added authorizations with pundit
hatcheta1/industrial-auth-1 pull request #2
Opened 2024-10-29 20:57 UTC by hatcheta1

- added pundit authorizations for Photos, Users, Comments, FollowRequests by setting up policies, authorizing actions
- secured by default

2024-10-30 19:01 UTC, armstrca commented
![Screenshot 2024-10-30 135112](https://github.com/user-attachments/assets/0c2ccb35-8418-4425-a043-7f36d027f005)
You don't need this flash to appear twice
![Screenshot 2024-10-30 135355](https://github.com/user-attachments/assets/20c8e99e-ef0d-4210-b2bc-cb6df2315769)
This is only happening at `root/alice`. Should not be display edit and delete icons for comments that don't belong to `current_user`
![Screenshot 2024-10-30 135431](https://github.com/user-attachments/assets/5d8e73af-3523-4fcc-806b-709ff9a4fcd7)
Deleting someone else's comment does not work, but editing does. Shouldn't be able to even attempt either, though.

2024-10-30 19:05 UTC, armstrca commented on app/controllers/comments_controller.rb
> +    authorize @comment
Are you sure lines 3, 17, and 75 make sense as written?

2024-10-30 19:07 UTC, armstrca commented on app/controllers/follow_requests_controller.rb
> +  before_action :authorize_follow_request, except: [:new, :create]
Why not new?

2024-10-30 19:08 UTC, armstrca commented on app/controllers/follow_requests_controller.rb
> +    authorize @follow_request
Is this different from `authorize_follow_request`?

2024-10-30 19:13 UTC, armstrca commented on app/controllers/follow_requests_controller.rb
> +        authorize @follow_request
Do you need this here?

2024-10-30 19:15 UTC, armstrca commented on app/controllers/photos_controller.rb
> +  before_action :authorize_photo, except: [:new, :create]
Why not new or create?

2024-10-30 19:15 UTC, armstrca commented on app/controllers/comments_controller.rb
> +  before_action :authorize_comment, except: [:new, :create]
Why not new or create?

2024-10-30 19:16 UTC, armstrca commented on app/controllers/photos_controller.rb
> +    authorize @photo
Same question as in other controllers

2024-10-30 19:16 UTC, armstrca commented on app/controllers/photos_controller.rb
> +        authorize @photo
Do you need this here?

2024-10-30 19:18 UTC, armstrca commented on app/controllers/users_controller.rb
> +  end
Don't need unused routes

2024-10-30 19:19 UTC, armstrca commented on app/policies/comment_policy.rb
> +    user == comment.author
the issue referenced in the screenshots is probably that this should be `@comment` rather than `comment`

2024-10-31 16:42 UTC, merrillhuang requested changes

2024-10-31 16:42 UTC, merrillhuang commented on app/policies/comment_policy.rb
Comments index route is not protected. You returned false in the comments policy and called authorize in the comments_controller in index method, but what is the declared instance variable in index and what instance variable is passed to authorize in your authorize comment method?

2024-11-01 14:28 UTC, merrillhuang approved these changes
Looks good!

2024-11-01 17:34 UTC, armstrca commented on app/controllers/comments_controller.rb
> +    authorize @comments
Nitpik: could remove this line if `authorize_comment` also handled @comments like so:

```ruby
    def authorize_comment
      authorize (@comment || Comment)
    end
```

Then you'd include `:index` in the `before_action` as well. But not a requirement for the assignment.

2024-11-01 17:48 UTC, armstrca approved these changes

2024-11-01 20:54 UTC, dgarcia13-99 commented on app/controllers/comments_controller.rb
> +  before_action :authorize_comment, except: [:index, :new, :create]
nice job adding authorization to 'show' 'edit' 'update', and 'destroy' actions!

2024-11-01 21:18 UTC, dgarcia13-99 approved these changes
You did a great job of defining clear policies and securing by default!

2024-11-01 21:18 UTC, dgarcia13-99 commented on app/controllers/follow_requests_controller.rb
> +    def authorize_follow_request
nice job adding a private method to facilitate authorization

2024-11-01 21:18 UTC, dgarcia13-99 commented on app/controllers/comments_controller.rb
> +      authorize(@comment || Comment)
nice job! You could even move this to the before_action and after_action so you don't have define the private method here. Either way, it works!

2024-11-01 21:18 UTC, dgarcia13-99 commented on app/controllers/users_controller.rb
> +  end
nice job using the before_action to handle the authorization for these actions!

2024-11-01 21:18 UTC, dgarcia13-99 commented on app/policies/comment_policy.rb
> +  def update?
nice job only allowing the current user to update and delete their own comments

2024-11-01 21:18 UTC, dgarcia13-99 commented on app/policies/follow_request_policy.rb
> +    !follow_request.recipient.followers.include?(user)
nice approach!

2024-11-01 21:18 UTC, dgarcia13-99 commented on app/views/comments/_comment.html.erb
> +      <% if current_user == comment.author %>
nice job hiding the edit feature for comments that don't belong to the current user

2024-11-22 20:41 UTC, merged